<%@ Page Language="C#" AutoEventWireup="true" CodeFile="34GridView_Edit.aspx.cs" Inherits="_34GridView_Edit" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ScoresConnectionString %>"
             SelectCommand="SELECT * FROM [StudentScores]"
             UpdateCommand="update [StudentScores] set Name=@Name, Address=@Address,Chinese=@Chinese,English=@English,Mathematics=@Mathematics,Class=@Class where StudentNo=@StudentNo"
            DeleteCommand="delete from [StudentScores] where StudentNo=@StudentNo"
            ></asp:SqlDataSource>

        <asp:GridView ID="GridView1" runat="server" OnRowDataBound="GridView1_RowDataBound" DataSourceID="SqlDataSource1" DataKeyNames="StudentNo" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"></asp:GridView>

          <hr />

        <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" DataKeyNames="StudentNo" DataSourceID="SqlDataSource1" OnRowDataBound="GridView2_RowDataBound">
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="StudentNo" HeaderText="StudentNo" ReadOnly="True" SortExpression="StudentNo" />
                <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                <asp:BoundField DataField="Chinese" HeaderText="Chinese" SortExpression="Chinese" />
                <asp:BoundField DataField="English" HeaderText="English" SortExpression="English" />
                <asp:BoundField DataField="Mathematics" HeaderText="Mathematics" SortExpression="Mathematics" />
                <asp:BoundField DataField="Class" HeaderText="Class" SortExpression="Class" />

                <asp:CommandField ButtonType="Button" ShowDeleteButton="True" ShowEditButton="True" />

            </Columns>
        </asp:GridView>
    </div>
    </form>
</body>
</html>
